- id: '1712296895921'
  alias: Play glz Friday 11:58
  description: ''
  trigger:
  - platform: time
    at: '11:58:00'
  condition:
  - condition: time
    weekday:
    - fri
  - condition: state
    entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
    state: 'off'
  - condition: or
    conditions:
    - condition: device
      device_id: 7896a9269282b5af07489f4edd966b28
      domain: media_player
      entity_id: 9c758cedfcec0f2a98fcc20f75d02648
      type: is_paused
    - condition: device
      device_id: 7896a9269282b5af07489f4edd966b28
      domain: media_player
      entity_id: 9c758cedfcec0f2a98fcc20f75d02648
      type: is_idle
  - condition: zone
    entity_id: person.zhr
    zone: zone.home
  action:
  - service: script.radio_galei_zahal
    metadata: {}
    data: {}
  mode: single
- id: '1712297018032'
  alias: Kan g Friday 13:00
  description: ''
  trigger:
  - platform: time
    at: '13:00:00'
  condition:
  - condition: time
    weekday:
    - fri
  - condition: state
    entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
    state: 'off'
  - condition: or
    conditions:
    - condition: device
      device_id: 7896a9269282b5af07489f4edd966b28
      domain: media_player
      entity_id: 9c758cedfcec0f2a98fcc20f75d02648
      type: is_paused
    - condition: device
      device_id: 7896a9269282b5af07489f4edd966b28
      domain: media_player
      entity_id: 9c758cedfcec0f2a98fcc20f75d02648
      type: is_idle
  action:
  - service: script.radio_kan_g
    data: {}
  mode: single
- id: '1712769427085'
  alias: Trigger 4 after noon radio
  description: ''
  trigger:
  - platform: time
    at: '16:00:00'
  condition:
  - condition: state
    entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
    state: 'off'
  - condition: zone
    entity_id: person.zhr
    zone: zone.home
  - condition: time
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
  action:
  - service: script.ask_for_4_after_noon_radio
    metadata: {}
    data: {}
  mode: single
- id: '1721359874047'
  alias: Trigger ארון השירים היהודי
  description: ''
  trigger:
  - platform: time
    at: 08:00:00
  condition:
  - condition: time
    weekday:
    - fri
  - condition: state
    state: 'off'
    entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
  - condition: device
    device_id: 8ef6a86daebbb51a8c7766df58661c4b
    domain: device_tracker
    entity_id: df33579cfb8dc5f962c3ba4d1aaa286b
    type: is_home
  action:
  - service: script.ask_baruch_for_kan_g
    metadata: {}
    data: {}
  mode: single
- id: '1722881168850'
  alias: If Mazgan should be on
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.is_mazgan_should_be_enabled
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: script.mazgan_cool_baruch_confirm
    metadata: {}
    data: {}
  mode: single
- id: '1722886260971'
  alias: Mazgan from cool to dry
  description: ''
  trigger:
  - platform: device
    device_id: 3daeb7afe3a86c54a308f1f0efd58f89
    domain: climate
    entity_id: 946a669e8b6968b40a237f5126631b0c
    type: hvac_mode_changed
    to: cool
    for:
      hours: 4
      minutes: 0
      seconds: 0
  condition: []
  action:
  - sequence:
    - parallel:
      - service: notify.mobile_app_baruch_phone
        metadata: {}
        data:
          message: רוצה לעבור למצב טיפה?
          title: מזגן
          data:
            actions:
            - action: 'YES'
              title: כן
            - action: 'NO'
              title: לא
      - service: notify.mobile_app_galaxy_watch6_classic_6zxw
        data:
          data:
            actions:
            - action: 'YES'
              title: כן
            - action: 'NO'
              title: ל
          message: רוצה לעבור למצב טיפה?
          title: מזגן
    - wait_for_trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: 'YES'
        id: confirmable_yes
      continue_on_timeout: false
      timeout:
        hours: 0
        minutes: 15
        seconds: 0
        milliseconds: 0
    - if:
      - condition: template
        value_template: '{{ wait.trigger.event.data.action == "YES" }}'
      then:
      - device_id: 3daeb7afe3a86c54a308f1f0efd58f89
        domain: climate
        entity_id: 946a669e8b6968b40a237f5126631b0c
        type: set_hvac_mode
        hvac_mode: dry
  mode: single
- id: '1722949510202'
  alias: Mazgan dry to cool
  description: ''
  trigger:
  - platform: device
    device_id: 3daeb7afe3a86c54a308f1f0efd58f89
    domain: climate
    entity_id: 946a669e8b6968b40a237f5126631b0c
    type: hvac_mode_changed
    to: dry
    for:
      hours: 0
      minutes: 30
      seconds: 0
  condition: []
  action:
  - sequence:
    - parallel:
      - service: notify.mobile_app_baruch_phone
        metadata: {}
        data:
          message: רוצה לעבור חזרה למצב קירור?
          title: מזגן
          data:
            actions:
            - action: 'YES'
              title: כן
            - action: 'NO'
              title: לא
      - service: notify.mobile_app_galaxy_watch6_classic_6zxw
        data:
          data:
            actions:
            - action: 'YES'
              title: כן
            - action: 'NO'
              title: ל
          message: רוצה לעבור חזרה למצב קירור?
          title: מזגן
    - wait_for_trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: 'YES'
        id: confirmable_yes
      continue_on_timeout: false
      timeout:
        hours: 0
        minutes: 15
        seconds: 0
        milliseconds: 0
    - if:
      - condition: template
        value_template: '{{ wait.trigger.event.data.action == "YES" }}'
      then:
      - device_id: 3daeb7afe3a86c54a308f1f0efd58f89
        domain: climate
        entity_id: 946a669e8b6968b40a237f5126631b0c
        type: set_hvac_mode
        hvac_mode: cool
  mode: single
- id: '1725150648817'
  alias: זהר - בית
  description: ''
  use_blueprint:
    path: homeassistant/notify_leaving_zone.yaml
    input:
      person_entity: person.zhr
      zone_entity: zone.home
      notify_device: 8ef6a86daebbb51a8c7766df58661c4b
- id: '1725150957123'
  alias: 'נורות - סטטוס '
  description: ''
  trigger:
  - platform: device
    type: changed_states
    device_id: c6beff2f34d8b7b5468d29f116da0d61
    entity_id: 089bd4f2880f1f82c89f24622321e944
    domain: light
  - platform: device
    type: changed_states
    device_id: 3e1275de086f4d16cf7a9c1462791943
    entity_id: e8f9b54b4e931c17880ea49ac00ac743
    domain: light
  - platform: state
    entity_id:
    - light.kitchen
    - light.carpet
  condition: []
  action:
  - action: notify.mobile_app_baruch_phone
    metadata: {}
    data:
      title: נורה
      message: נורה
  mode: single
- id: '1725161057865'
  alias: זהר - הגן השקוף
  description: ''
  use_blueprint:
    path: homeassistant/notify_leaving_zone.yaml
    input:
      person_entity: person.zhr
      zone_entity: zone.hgn_hshqvp
      notify_device: 8ef6a86daebbb51a8c7766df58661c4b
