- id: '1712232583706'
  alias: Mazgan
  description: להדליק מזגן מעל 27 מעלות
  trigger:
  - platform: device
    device_id: 3daeb7afe3a86c54a308f1f0efd58f89
    domain: climate
    entity_id: 946a669e8b6968b40a237f5126631b0c
    type: current_temperature_changed
    above: 27
  condition:
  - condition: state
    entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
    state: 'off'
    enabled: false
  action:
  - device_id: 3daeb7afe3a86c54a308f1f0efd58f89
    domain: climate
    entity_id: 946a669e8b6968b40a237f5126631b0c
    type: set_hvac_mode
    hvac_mode: fan_only
  mode: single
- id: '1712247462364'
  alias: כיבוי מזגן
  description: לכבות מזגן מתחת 25 מעלות
  trigger:
  - platform: device
    device_id: 3daeb7afe3a86c54a308f1f0efd58f89
    domain: climate
    entity_id: 946a669e8b6968b40a237f5126631b0c
    type: current_temperature_changed
    below: 26
  condition:
  - condition: state
    entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
    state: 'off'
    enabled: false
  - condition: not
    conditions:
    - condition: device
      device_id: 3daeb7afe3a86c54a308f1f0efd58f89
      domain: climate
      entity_id: 946a669e8b6968b40a237f5126631b0c
      type: is_hvac_mode
      hvac_mode: 'off'
  action:
  - device_id: 3daeb7afe3a86c54a308f1f0efd58f89
    domain: climate
    entity_id: 946a669e8b6968b40a237f5126631b0c
    type: set_hvac_mode
    hvac_mode: 'off'
  mode: single
- id: '1712296895921'
  alias: Play glz Friday 11:58
  description: ''
  trigger:
  - platform: time
    at: '11:58:00'
  condition:
  - condition: time
    weekday:
    - fri
  - condition: state
    entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
    state: 'off'
  - condition: or
    conditions:
    - condition: device
      device_id: 7896a9269282b5af07489f4edd966b28
      domain: media_player
      entity_id: 9c758cedfcec0f2a98fcc20f75d02648
      type: is_paused
    - condition: device
      device_id: 7896a9269282b5af07489f4edd966b28
      domain: media_player
      entity_id: 9c758cedfcec0f2a98fcc20f75d02648
      type: is_idle
  - condition: zone
    entity_id: person.zhr
    zone: zone.home
  action:
  - service: script.radio_galei_zahal
    metadata: {}
    data: {}
  mode: single
- id: '1712297018032'
  alias: Kan g Friday 13:00
  description: ''
  trigger:
  - platform: time
    at: '13:00:00'
  condition:
  - condition: time
    weekday:
    - fri
  - condition: state
    entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
    state: 'off'
  - condition: or
    conditions:
    - condition: device
      device_id: 7896a9269282b5af07489f4edd966b28
      domain: media_player
      entity_id: 9c758cedfcec0f2a98fcc20f75d02648
      type: is_paused
    - condition: device
      device_id: 7896a9269282b5af07489f4edd966b28
      domain: media_player
      entity_id: 9c758cedfcec0f2a98fcc20f75d02648
      type: is_idle
  action:
  - service: script.radio_kan_g
    data: {}
  mode: single
- id: '1712331287593'
  alias: שבת שלום
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.jewish_calendar_issur_melacha_in_effect
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: tts.speak
    metadata: {}
    data:
      cache: true
      media_player_entity_id: media_player.living_room_speaker
      message: שבת שלום
      language: Hebrew
  - service: media_player.media_stop
    metadata: {}
    data: {}
    target:
      device_id: 7896a9269282b5af07489f4edd966b28
  mode: single
- id: '1712764002022'
  alias: 'Leaving the house '
  description: ''
  trigger:
  - platform: state
    entity_id:
    - zone.home
    to: '0'
  condition: []
  action:
  - service: media_player.media_stop
    continue_on_error: true
    metadata: {}
    data: {}
    target:
      device_id: 7896a9269282b5af07489f4edd966b28
  - service: light.turn_off
    continue_on_error: true
    metadata: {}
    data: {}
    target:
      device_id: 3e1275de086f4d16cf7a9c1462791943
  - service: notify.mobile_app_baruch_phone
    metadata: {}
    data:
      message: 'Leaving the house '
  - type: turn_off
    device_id: ddda0c7e7b0177094ca218497c439fdb
    entity_id: 514fd8e508cdcb7dbb6d55e7c0870d8d
    domain: fan
  - type: turn_off
    device_id: 676073374993afc6187c393432dda2ef
    entity_id: 0c79028992a817dfbe8623fc115e32dd
    domain: switch
  mode: single
- id: '1712765888531'
  alias: Enter home
  description: ''
  trigger:
  - platform: state
    entity_id:
    - zone.home
    from: '0'
    to: '1'
  condition: []
  action:
  - service: light.turn_on
    metadata: {}
    data:
      color_temp: 153
      brightness: 255
    target:
      device_id: 3e1275de086f4d16cf7a9c1462791943
  mode: single
- id: '1712769427085'
  alias: Trigger 4 after noon radio
  description: ''
  trigger:
  - platform: time
    at: '16:00:00'
  condition:
  - condition: state
    entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
    state: 'off'
  - condition: zone
    entity_id: person.zhr
    zone: zone.home
  - condition: time
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
  action:
  - service: script.ask_for_4_after_noon_radio
    metadata: {}
    data: {}
  mode: single
