
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

jewish_calendar:
  language: hebrew
  # Tel Aviv
  latitude: 32.0853
  longitude: 34.7818
  candle_lighting_minutes_before_sunset: 20
