# Loads default set of integrations. Do not remove.
default_config:

# Allow Cloudflare Tunnel from Docker
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.105
    - 172.30.33.3
    - 127.0.0.1
    - ::1
    - 172.20.0.6
    - 192.168.0.0/24

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
# template: !include templates.yaml

# switch:
#   - platform: flux
#     lights:
#       - light.carpet
#       - light.kitchen
#     start_time: "7:00"
#     stop_time: "23:00"
#     start_colortemp: 40000
#     sunset_colortemp: 40000
#     stop_colortemp: 19000
#     brightness: 255
#     disable_brightness_adjust: true
#     mode: xy

rest:
  - resource: https://api.npmjs.org/downloads/point/last-week/use-route-as-state
    scan_interval: 43200 # 12 hours
    sensor:
      - name: npm_downloads.use_route_as_state
        value_template: "{{ value_json.downloads }}"
        unit_of_measurement: "downloads"
  - resource: https://api.npmjs.org/downloads/point/last-week/pursuit-rotor-task
    scan_interval: 43200 # 12 hours
    sensor:
      - name: npm_downloads.pursuit_rotor_task
        value_template: "{{ value_json.downloads }}"
        unit_of_measurement: "downloads"
  - resource: https://api.npmjs.org/downloads/point/last-week/electron-google-oauth2
    scan_interval: 43200 # 12 hours
    sensor:
      - name: npm_downloads.electron_google_oauth2
        value_template: "{{ value_json.downloads }}"
        unit_of_measurement: "downloads"
  
  - resource: https://script.google.com/macros/s/AKfycbyDkIaGizQpnhE3qXLOohmIj-P0q94tr6lnro8TX7aJ2lFivoC6uyffJfrFwOTJUTAwTw/exec?zmanim=true
    scan_interval: 43200 # 12 hours
    sensor:
      - name: "Tfilot Chol - Shaarit 1"
        value_template: "{{ value_json.tfilotChol.shaarit1 }}"
      - name: "Tfilot Chol - Shaarit 2"
        value_template: "{{ value_json.tfilotChol.shaarit2 }}"
      - name: "Tfilot Chol - Minha"
        value_template: "{{ value_json.tfilotChol.minha }}"
      - name: "Tfilot Chol - Arvit 1"
        value_template: "{{ value_json.tfilotChol.arvit1 }}"
      - name: "Tfilot Chol - Arvit 2"
        value_template: "{{ value_json.tfilotChol.arvit2 }}"

scrape:
  - resource: https://marketplace.visualstudio.com/items?itemName=baruchiro.url-title-preview
    scan_interval: 43200 # 12 hours
    sensor:
      - name: "URL Title Preview Downloads"
        select: ".installs-text"
        value_template: "{{ value.split(' ')[1] | int(-1) }}"
        icon: mdi:microsoft-visual-studio-code
  
  - resource: https://stackoverflow.com/users/839513/baruchiro
    scan_interval: 86400 # 24 hours
    sensor:
      - name: "Stack Overflow Reputation"
        select: "#stats .fs-body3"
        value_template: "{{ value.replace(',', '') | int }}"
        icon: mdi:stack-overflow
  
  - resource: https://nitter.privacydev.net/baruchiro
    scan_interval: 86400 # 24 hours
    sensor:
      - name: "Twitter Followers"
        select: ".followers .profile-stat-num"
        value_template: "{{ value.replace(',', '') | int }}"
        icon: mdi:twitter
