sensor:
  - platform: template
    sensors:
      devices_to_check_when_leaving:
        friendly_name: Devices to Check When Leaving
        unique_id: devices_to_check_when_leaving
        value_template: "ok"
        icon_template: "mdi:devices"
        attribute_templates:
          devices: >
            [
              {
                "entity_id": "climate.mm_d",
                "friendly_name": "מזגן ממ״ד",
                "off_state": "off",
                "turn_off_service": "climate.set_hvac_mode",
                "turn_off_data": {
                  "hvac_mode": "off"
                }
              },
              {
                "entity_id": "media_player.living_room_speaker",
                "friendly_name": "רמקול בסלון",
                "off_state": "idle",
                "turn_off_service": "media_player.media_stop"
              }
            ] 