radio_galei_zahal:
  alias: radio galei zahal
  sequence:
  - service: media_player.play_media
    target:
      entity_id: media_player.living_room_speaker
    data:
      media_content_id: media-source://radio_browser/962326cb-0601-11e8-ae97-52543be04c81
      media_content_type: audio/mpeg
    metadata:
      title: Galei Zahal
      thumbnail: ''
      media_class: music
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://radio_browser
      - media_content_type: music
        media_content_id: media-source://radio_browser/country/IL
  mode: single
  icon: mdi:radio
radio_kan_g:
  alias: radio kan g
  sequence:
  - service: media_player.play_media
    target:
      entity_id: media_player.living_room_speaker
    data:
      media_content_id: media-source://radio_browser/0fcffb77-b99e-11e9-acb2-52543be04c81
      media_content_type: audio/mpeg
    metadata:
      title: KAN gimel (real)
      thumbnail: https://kanweb.blob.core.windows.net/download/pictures/Logo_Color9_img_.png
      media_class: music
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://radio_browser
      - media_content_type: music
        media_content_id: media-source://radio_browser/country/IL
  mode: single
  icon: mdi:radio
ask_for_4_after_noon_radio:
  alias: Ask for 4 after noon Radio
  use_blueprint:
    path: homeassistant/confirmable_notification.yaml
    input:
      notify_device: b85fff6170a535d2566d4ea2ce88674f
      title: 4 אחרי הצהריים
      message: האם את רוצה להפעיל?
      confirm_text: כן
      dismiss_text: לא עכשיו
      confirm_action:
      - service: script.radio_galei_zahal
        metadata: {}
        data: {}
  icon: mdi:radio
ask_baruch_for_kan_g:
  alias: Ask Baruch for Kan G
  use_blueprint:
    path: homeassistant/confirmable_notification.yaml
    input:
      notify_device: 8ef6a86daebbb51a8c7766df58661c4b
      title: Ask for Kan g Baruch
      message: האם להפעיל "ארון השירים היהודי"?
      confirm_action:
      - service: script.radio_kan_g
        metadata: {}
        data: {}
  description: ''
  icon: mdi:bell
mazgan_cool:
  alias: Mazgan Cool
  sequence:
  - choose:
    - conditions:
      - condition: not
        conditions:
        - condition: device
          device_id: 3daeb7afe3a86c54a308f1f0efd58f89
          domain: climate
          entity_id: 946a669e8b6968b40a237f5126631b0c
          type: is_hvac_mode
          hvac_mode: cool
        alias: If Mazgan IS NOT cool
      sequence:
      - device_id: 3daeb7afe3a86c54a308f1f0efd58f89
        domain: climate
        entity_id: 946a669e8b6968b40a237f5126631b0c
        type: set_hvac_mode
        hvac_mode: cool
    - conditions:
      - condition: device
        device_id: 3daeb7afe3a86c54a308f1f0efd58f89
        domain: climate
        entity_id: 946a669e8b6968b40a237f5126631b0c
        type: is_hvac_mode
        hvac_mode: cool
        alias: If Mazgan IS cool
      sequence:
      - device_id: 3daeb7afe3a86c54a308f1f0efd58f89
        domain: climate
        entity_id: 946a669e8b6968b40a237f5126631b0c
        type: set_hvac_mode
        hvac_mode: 'off'
  description: ''
  icon: mdi:air-conditioner
mazgan_cool_baruch_confirm:
  alias: Mazgan Cool Baruch Confirm
  use_blueprint:
    path: homeassistant/confirmable_notification.yaml
    input:
      notify_device: 8ef6a86daebbb51a8c7766df58661c4b
      title: מזגן
      message: האם להדליק מזגן?
      confirm_text: להדליק
      confirm_action:
      - device_id: 3daeb7afe3a86c54a308f1f0efd58f89
        domain: climate
        entity_id: 946a669e8b6968b40a237f5126631b0c
        type: set_hvac_mode
        hvac_mode: cool
      dismiss_text: להתעלם
      dismiss_action: []
  description: ''
  icon: mdi:air-conditioner
unknown:
  alias: מאוורר חדר מצב שינה
  sequence:
  - action: fan.toggle
    metadata: {}
    data: {}
    target:
      device_id: ddda0c7e7b0177094ca218497c439fdb
  - action: fan.oscillate
    metadata: {}
    data:
      oscillating: true
    target:
      device_id: ddda0c7e7b0177094ca218497c439fdb
  - action: fan.set_preset_mode
    metadata: {}
    data:
      preset_mode: sleep
    target:
      device_id: ddda0c7e7b0177094ca218497c439fdb
  - action: fan.set_percentage
    metadata: {}
    data:
      percentage: 1
    target:
      device_id: ddda0c7e7b0177094ca218497c439fdb
  description: ''
  icon: mdi:fan
toggle_mamad_night_light:
  sequence:
  - if:
    - condition: or
      conditions:
      - condition: numeric_state
        entity_id: light.mamad
        attribute: brightness
        above: 10
      - condition: state
        entity_id: light.mamad
        state: 'off'
    then:
    - action: light.turn_on
      metadata: {}
      data:
        brightness_pct: 1
        rgb_color: "[{{ range(0, 256) | random }}, {{ range(0, 256) | random}},{{ range(0, 256) | random }}]"
      target:
        entity_id: light.mamad
      alias: 1 brightness random color
    else:
    - action: light.turn_on
      metadata: {}
      data:
        brightness_pct: 100
        kelvin: 6500
      target:
        entity_id: light.mamad
  alias: 'Toggle Mamad Night Light '
  description: ''
  icon: mdi:lightbulb-night
unknown_2:
  sequence:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.heat_spreader
  - delay:
      hours: 0
      minutes: 45
      seconds: 0
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.heat_spreader
  alias: מקלחת טליה
  description: ''
  icon: mdi:shower-head
