version: '3'
services:
  telegram-download-deamon:
    container_name: telegram-download-deamon
    image: baruchiro/telegram-download-daemon
    environment:
      TELEGRAM_DEAMON_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_DEAMON_API_HASH: ${TELEGRAM_API_HASH}
      TELEGRAM_DEAMON_CHANNEL: ${TELEGRAM_TV_CHANNEL_ID}
      TELEGRAM_DEAMON_DEST: "/downloads"
      TELEGRAM_DEAMON_SESSION_PATH: "/session"
    volumes:
      - tv-shows:/downloads
      - sessions:/session
    restart: unless-stopped
  
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./jellyfin/config/:/config
      - /cache
      - tv-shows:/media/tv-shows

volumes:
  sessions:
  tv-shows:
