version: '3'
services:
  telegram-download-deamon:
    image: docker.pkg.github.com/baruchiro/telegram-download-daemon/telegram-download-deamon
    environment:
      TELEGRAM_DEAMON_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_DEAMON_API_HASH: ${TELEGRAM_API_HASH}
      TELEGRAM_DEAMON_CHANNEL: ${TELEGRAM_TV_CHANNEL_ID}
      TELEGRAM_DEAMON_DEST: "/downloads"
      TELEGRAM_DEAMON_SESSION_PATH: "/session"
    volumes:
      - tv-shows:/downloads
      - sessions:/session
    restart: unless-stopped
  
  jellyfin:
    container_name: plex
    image: jellyfin/jellyfin
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./jellyfin/config/:/config
      - /cache
      - tv-shows:/media/tv-shows

  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    network_mode: host
    volumes:
      - ./home-assistant:/config
    env_file: shared.env
    restart: always
    network_mode: host

volumes:
  sessions:
  tv-shows:
