version: '3'
services:
  telegram-download-daemon:
    container_name: telegram-download-deamon
    image: baruchiro/telegram-download-daemon
    environment:
      TELEGRAM_DAEMON_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_DAEMON_API_HASH: ${TELEGRAM_API_HASH}
      TELEGRAM_DAEMON_CHANNEL: ${TELEGRAM_TV_CHANNEL_ID}
      TELEGRAM_DAEMON_DEST: "/downloads"
      TELEGRAM_DAEMON_SESSION_PATH: "/session"
    volumes:
      - tv-shows:/downloads
      - sessions:/session
    restart: unless-stopped
  
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./jellyfin/config/:/config
      - /cache
      - tv-shows:/media/tv-shows

  fireflyiii:
    container_name: firefly
    image: jc5x/firefly-iii
    volumes: 
      - firefly_iii_export:/var/www/firefly-iii/storage/export
      - firefly_iii_upload:/var/www/firefly-iii/storage/upload
    env_file: fireflyiii.env
    ports:
      - 80:80
    depends_on:
      - fireflyiiidb
  
  fireflyiiidb:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=firefly
      - POSTGRES_PASSWORD=secret_firefly_password
    volumes:
      - firefly_iii_db:/var/lib/postgresql/data


volumes:
  sessions:
  tv-shows:
  firefly_iii_export:
  firefly_iii_upload:
  firefly_iii_db:
