version: '3'
services:
  telegram-download-daemon:
    container_name: telegram-download-deamon
    image: baruchiro/telegram-download-daemon
    environment:
      TELEGRAM_DAEMON_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_DAEMON_API_HASH: ${TELEGRAM_API_HASH}
      TELEGRAM_DAEMON_CHANNEL: ${TELEGRAM_TV_CHANNEL_ID}
      TELEGRAM_DAEMON_DEST: "/downloads"
      TELEGRAM_DAEMON_SESSION_PATH: "/session"
    volumes:
      - tv-shows:/downloads
      - sessions:/session
    restart: unless-stopped
  
  jellyfin:
    # port 8096
    container_name: jellyfin
    image: jellyfin/jellyfin
    restart: unless-stopped
    network_mode: host
    env_file:
      - shared.env
    volumes:
      - jellyfin:/config
      - jellyfin-cache:/cache
      - all-media:/media
      - tv-shows:/media/tv-shows
  
  jackett:
    # port 9117
    image: linuxserver/jackett
    container_name: jackett
    network_mode: host
    env_file:
      - shared.env
    environment:
      - PUID=0
      - PGID=0
      - AUTO_UPDATE=true
    volumes:
      - jackett:/config
      - downloads:/downloads
    restart: unless-stopped
  
  deluge:
    # port 8112
    image: linuxserver/deluge
    container_name: deluge
    network_mode: host
    restart: unless-stopped
    env_file:
      - shared.env
    volumes:
      - deluge:/config
      - downloads:/downloads

  sonarr:
    # port 8989
    image: linuxserver/sonarr:preview
    container_name: sonarr
    network_mode: host
    depends_on:
      - jackett
      - deluge
    env_file:
      - shared.env
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - tv-shows:/tv
      - sonarr:/config
      - downloads:/downloads
    restart: unless-stopped
  
  bazarr:
    # port 6767
    image: linuxserver/bazarr
    container_name: bazarr
    network_mode: host
    env_file:
      - shared.env
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - bazarr:/config
      - tv-shows:/tv
    restart: unless-stopped

  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    env_file:
      - shared.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data


volumes:
  sessions:
  all-media:
  tv-shows:
  downloads:
  
  # Configs
  jellyfin:
  jellyfin-cache:
  jackett:
  deluge:
  sonarr:
  bazarr:
  portainer:
