services:
  # telegram-download-daemon:
  #   container_name: telegram-download-daemon
  #   image: baruchiro/telegram-download-daemon
  #   environment:
  #     TELEGRAM_DAEMON_API_ID: ${TELEGRAM_DAEMON_API_ID}
  #     TELEGRAM_DAEMON_API_HASH: ${TELEGRAM_DAEMON_API_HASH}
  #     TELEGRAM_DAEMON_CHANNEL: ${TELEGRAM_TV_CHANNEL_ID}
  #     TELEGRAM_DAEMON_DEST: "/downloads"
  #     TELEGRAM_DAEMON_TEMP: "/telegram-temp"
  #     TELEGRAM_DAEMON_SESSION_PATH: "/session"
  #   volumes:
  #     - tv-shows:/downloads
  #     - sessions:/session
  #   restart: unless-stopped

  jellyfin:
    # port 8096
    container_name: jellyfin
    image: jellyfin/jellyfin
    restart: unless-stopped
    network_mode: host
    env_file:
      - shared.env
    volumes:
      - jellyfin:/config
      - jellyfin-cache:/cache
      - all-media:/media
      - tv-shows:/media/tv-shows
      - movies:/media/movies

  jackett:
    # port 9117
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    network_mode: host
    env_file:
      - shared.env
    environment:
      - PUID=0
      - PGID=0
      - AUTO_UPDATE=true
    volumes:
      - jackett:/config
      - downloads:/downloads
    restart: unless-stopped

  deluge:
    # port 8112
    image: ghcr.io/linuxserver/deluge:2.1.1
    container_name: deluge
    network_mode: host
    restart: unless-stopped
    env_file:
      - shared.env
    volumes:
      - deluge:/config
      - downloads:/downloads

  sonarr:
    # port 8989
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    network_mode: host
    depends_on:
      - jackett
      - deluge
    env_file:
      - shared.env
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - tv-shows:/tv
      - sonarr:/config
      - downloads:/downloads
    restart: unless-stopped

  radarr:
    # port 7878
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    network_mode: host
    depends_on:
      - jackett
      - deluge
    env_file:
      - shared.env
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - movies:/movies
      - radarr:/config
      - downloads:/downloads
    restart: unless-stopped

  bazarr:
    # port 6767
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    network_mode: host
    env_file:
      - shared.env
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - bazarr:/config
      - tv-shows:/tv
      - movies:/movies
    restart: unless-stopped

  jellyseerr:
    # port 5055
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    network_mode: host
    env_file:
      - shared.env
    volumes:
      - jellyseerr:/app/config
    restart: unless-stopped

  portainer:
    # port 9000
    image: portainer/portainer-ce
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    env_file:
      - shared.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data

  homeassistant:
    # port 8123
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    env_file:
      - shared.env
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    privileged: true
    network_mode: host

  mqtt:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    volumes:
      - mosquitto-data:/mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    command: 'mosquitto -c /mosquitto-no-auth.conf'

  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    volumes:
      - ./zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    env_file:
      - shared.env
    ports:
      - 8080:8080
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
  # n8n:
  #   # port 5678
  #   container_name: n8n
  #   image: docker.n8n.io/n8nio/n8n:latest
  #   network_mode: host
  #   env_file:
  #     - shared.env
  #   environment:
  #     - N8N_SECURE_COOKIE=false
  #   volumes:
  #       - n8n:/home/node/.n8n

  # code-server:
  #   # port 8443
  #   image: lscr.io/linuxserver/code-server:latest
  #   container_name: code-server
  #   privileged: true
  #   env_file:
  #     - shared.env
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     # - PASSWORD=password #optional
  #     # - HASHED_PASSWORD= #optional
  #     # - SUDO_PASSWORD=password #optional
  #     # - SUDO_PASSWORD_HASH= #optional
  #     - PROXY_DOMAIN=code.${DOMAIN} #optional
  #     - DEFAULT_WORKSPACE=/sources/home-server #optional
  #   volumes:
  #     - code-server:/config
  #     - ./:/sources/home-server
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   ports:
  #     - 8443:8443
  #   restart: unless-stopped

  nocodb:
    depends_on:
      nocodb_mysql:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      NC_DB: "mysql2://nocodb_mysql:3306?u=noco&p=password&d=root_db"
    image: "nocodb/nocodb:latest"
    ports:
      - "8765:8080"
    restart: always
    volumes:
      - "nocodb_data:/usr/app/data"

  nocodb_mysql:
    environment:
      MYSQL_DATABASE: root_db
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: noco
    healthcheck:
      retries: 10
      test:
        - CMD
        - mysqladmin
        - ping
        - "-h"
        - localhost
      timeout: 20s
    image: "mysql:8.3.0"
    restart: always
    volumes:
      - "nocodb_mysql_data:/var/lib/mysql"
    ports:
      - "3306:3306"
  #    below line shows how to change charset and collation
  #    uncomment it if necessary
  #    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  nocobase:
    image: nocobase/nocobase:latest
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - shared.env
    environment:
      # The application's secret key, used to generate user tokens, etc.
      # If APP_KEY is changed, old tokens will also become invalid.
      # It can be any random string, and make sure it is not exposed.
      - APP_KEY=${NOCOBASRE_APP_KEY}
      # Database type, supports postgres, mysql, mariadb
      - DB_DIALECT=mysql
      # Database host, can be replaced with the IP of an existing database server
      - DB_HOST=mysql
      # Database name
      - DB_DATABASE=nocobase
      # Database user
      - DB_USER=${MYSQL_USER}
      # Database password
      - DB_PASSWORD=${MYSQL_PASSWORD}
      # Whether to convert table and field names to snake case
      - DB_UNDERSCORED=true
    volumes:
      - nocobase:/app/nocobase/storage
    ports:
      - "13000:13000"

  mysql:
    image: mysql:8
    env_file:
      - shared.env
    environment:
      # MYSQL_DATABASE: nocobase
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:
      retries: 10
      test:
        - CMD
        - mysqladmin
        - ping
        - "-h"
        - localhost
      timeout: 20s
    restart: always
    entrypoint: sh -c " echo 'CREATE DATABASE IF NOT EXISTS nocodb;' > /docker-entrypoint-initdb.d/0-init.sql; echo 'CREATE DATABASE IF NOT EXISTS nocobase;' >> /docker-entrypoint-initdb.d/0-init.sql; echo 'GRANT ALL PRIVILEGES ON nocodb.* TO \"${MYSQL_USER}\"@\"%\";' >> /docker-entrypoint-initdb.d/0-init.sql; echo 'GRANT ALL PRIVILEGES ON nocobase.* TO \"${MYSQL_USER}\"@\"%\";' >> /docker-entrypoint-initdb.d/0-init.sql; echo 'FLUSH PRIVILEGES;' >> /docker-entrypoint-initdb.d/0-init.sql; /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci "
    volumes:
      - mysql:/var/lib/mysql
      - mysql-backup:/var/lib/backup
      - ./mysql/scripts:/var/lib/scripts
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.export-people.schedule: "@daily"
      ofelia.job-exec.export-people.command: "sh -c '/var/lib/scripts/backup.sh /var/lib/backup'"

  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - paperless-web
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-local.my-test-job.schedule: "@every 5s"
      ofelia.job-local.my-test-job.command: "date"

  # Docker Compose file for running paperless from the docker container registry.
  # This file contains everything paperless needs to run.
  # Paperless supports amd64, arm and arm64 hardware.
  # All compose files of paperless configure paperless in the following way:
  #
  # - Paperless is (re)started on system boot, if it was running before shutdown.
  # - Docker volumes for storing data are managed by Docker.
  # - Folders for importing and exporting files are created in the same directory
  #   as this file and mounted to the correct folders inside the container.
  # - Paperless listens on port 8000.
  #
  # SQLite is used as the database. The SQLite file is stored in the data volume.
  #
  # In addition to that, this Docker Compose file adds the following optional
  # configurations:
  #
  # - Apache Tika and Gotenberg servers are started with paperless and paperless
  #   is configured to use these services. These provide support for consuming
  #   Office documents (Word, Excel, Power Point and their LibreOffice counter-
  #   parts.
  #
  # To install and update paperless with this file, do the following:
  #
  # - Copy this file as 'docker-compose.yml' and the files 'docker-compose.env'
  #   and '.env' into a folder.
  # - Run 'docker compose pull'.
  # - Run 'docker compose run --rm paperless-web createsuperuser' to create a user.
  # - Run 'docker compose up -d'.
  #
  # For more extensive installation and update instructions, refer to the
  # documentation.
  # TODO: use shared redis
  paperless-broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - paperless-redisdata:/data

  paperless-web:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - paperless-broker
      - paperless-gotenberg
      - paperless-tika
    ports:
      - "3355:8000"
    volumes:
      - paperless-data:/usr/src/paperless/data
      - paperless-media:/usr/src/paperless/media
      - paperless-export:/usr/src/paperless/export
      - paperless-consume:/usr/src/paperless/consume
      - ./paperless/scripts:/usr/src/paperless/scripts
    env_file: paperless.env
    environment:
      PAPERLESS_REDIS: redis://paperless-broker:6379
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://paperless-gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://paperless-tika:9998
      PAPERLESS_URL: https://paperless.${DOMAIN}
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.datecron.schedule: "@every 12h"
      ofelia.job-exec.datecron.command: "document_exporter ../export --delete --no-archive --no-thumbnail --use-folder-prefix --split-manifest"

  paperless-gotenberg:
    image: docker.io/gotenberg/gotenberg:7.10
    restart: unless-stopped

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  paperless-tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped

  obsidian-livesync:
    image: couchdb
    container_name: obsidian-livesync
    user: 1000:1000
    environment:
      - COUCHDB_USER=${OBSIDIAN_COUCHDB_USER} # enter the desired CouchDB admin username
      - COUCHDB_PASSWORD=${OBSIDIAN_COUCHDB_PASSWORD} # enter the desired CouchDB admin password
    volumes:
      - obsidian-data:/opt/couchdb/data
      - ./obsidian/local.ini:/opt/couchdb/etc/local.ini
    ports:
      - 5984:5984
    restart: unless-stopped

  node-red:
    # port 1880
    # Dev: docker run -p 1880:1880 -v $(pwd)/node-red:/data --entrypoint="" --env-file .env nodered/node-red /bin/sh -c "npm install --prefix /data --unsafe-perm --no-update-notifier --no-fund --only=production && npm --no-update-notifier --no-fund start --cache /data/.npm -- --userDir /data"
    image: nodered/node-red
    env_file:
      - shared.env
    network_mode: host
    entrypoint: >
      sh -c " npm install --prefix /data --unsafe-perm --no-update-notifier --no-fund --only=production && npm --no-update-notifier --no-fund start --cache /data/.npm -- --userDir /data"
    environment:
      NODE_RED_CREDENTIAL_SECRET: ${NODE_RED_CREDENTIAL_SECRET}
    volumes:
      - ./node-red:/data
    restart: unless-stopped

  postiz:
    image: ghcr.io/gitroomhq/postiz-app:latest
    container_name: postiz
    restart: always
    environment:
      # You must change these. Replace `postiz.your-server.com` with your DNS name - what your web browser sees.
      MAIN_URL: "https://postiz.${DOMAIN}"
      FRONTEND_URL: "https://postiz.${DOMAIN}"
      NEXT_PUBLIC_BACKEND_URL: "https://postiz.${DOMAIN}/api"
      # JWT_SECRET: "postiz.env"

      # These defaults are probably fine, but if you change your user/password, update it in the
      # postiz-postgres or postiz-redis services below.
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/postiz-db-local"
      REDIS_URL: "redis://redis:6379"
      BACKEND_INTERNAL_URL: "http://localhost:3000"
      IS_GENERAL: "true" # Required for self-hosting.
      # The container images are pre-configured to use /uploads for file storage.
      # You probably should not change this unless you have a really good reason!
      STORAGE_PROVIDER: "local"
      UPLOAD_DIRECTORY: "/uploads"
      NEXT_PUBLIC_UPLOAD_DIRECTORY: "/uploads"
    env_file:
      - postiz.env
    volumes:
      - postiz-config:/config/
      - postiz-uploads:/uploads/
    ports:
      - 5000:5000
    networks:
      - postiz-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: main_db
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - default
      - postiz-network
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d main_db
      interval: 10s
      timeout: 3s
      retries: 3

  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - redis-data:/data
    networks:
      - default
      - postiz-network

volumes:
  sessions:
  all-media:
  tv-shows:
  movies:
  downloads:

  nocodb_mysql_data:
  nocodb_data:

  redis-data:
  postgres:
  mysql:
  nocobase:

  obsidian-data:

  mosquitto-data:

  postiz-config:
  postiz-uploads:

  # Configs
  jellyfin:
  jellyfin-cache:
  jackett:
  deluge:
  sonarr:
  radarr:
  bazarr:
  jellyseerr:
  portainer:
  n8n:

  paperless-redisdata:
  paperless-data:
  paperless-media:
  paperless-export:
    driver: rclone
    driver_opts:
      remote: 'remote-gdrive:paperless'
      allow_other: 'true'
      vfs_cache_mode: full
      poll_interval: 0
  paperless-consume:

  mysql-backup:
    driver: rclone
    driver_opts:
      remote: 'remote-gdrive:nocobase-backup'
      allow_other: 'true'
      vfs_cache_mode: full
      poll_interval: 0

networks:
  default:
  postiz-network:
