services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096"
    env_file:
      - shared.env
    volumes:
      - jellyfin:/config
      - jellyfin-cache:/cache
      - all-media:/media
      - tv-shows:/media/tv-shows
      - movies:/media/movies
    networks:
      - media_net

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    ports:
      - "5055:5055"
    env_file:
      - shared.env
    volumes:
      - jellyseerr:/app/config
    restart: unless-stopped
    networks:
      - media_net
    depends_on:
      - jellyfin

  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    ports:
      - "9117:9117"
    env_file:
      - shared.env
    environment:
      - PUID=0
      - PGID=0
      - AUTO_UPDATE=true
    volumes:
      - jackett:/config
      - downloads:/downloads
    restart: unless-stopped
    networks:
      - media_net

  deluge:
    image: ghcr.io/linuxserver/deluge:2.1.1
    container_name: deluge
    ports:
      - "8112:8112"
    restart: unless-stopped
    env_file:
      - shared.env
    volumes:
      - deluge:/config
      - downloads:/downloads
    networks:
      - media_net

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    ports:
      - "8989:8989"
    depends_on:
      - jackett
      - deluge
    env_file:
      - shared.env
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - tv-shows:/tv
      - sonarr:/config
      - downloads:/downloads
    restart: unless-stopped
    networks:
      - media_net

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    ports:
      - "7878:7878"
    depends_on:
      - jackett
      - deluge
    env_file:
      - shared.env
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - movies:/movies
      - radarr:/config
      - downloads:/downloads
    restart: unless-stopped
    networks:
      - media_net

  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    ports:
      - "6767:6767"
    env_file:
      - shared.env
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - bazarr:/config
      - tv-shows:/tv
      - movies:/movies
    restart: unless-stopped
    networks:
      - media_net
    depends_on:
      - sonarr
      - radarr

networks:
  media_net:
    name: media_network
    driver: bridge

volumes:
  jellyfin:
  jellyfin-cache:
  all-media:
  tv-shows:
  movies:
  jackett:
  downloads:
  deluge:
  sonarr:
  radarr:
  bazarr:
  jellyseerr:
